/*
        GENERATED BY GPT
 */


import java.util.Scanner;

public class MusicFileCalculator {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Enter the number of songs: ");
        int numSongs = scanner.nextInt();

        System.out.print("Enter the bitrate (in kbps): ");
        int bitrate = scanner.nextInt();

        System.out.print("Enter the average duration of songs (in minutes): ");
        int avgDuration = scanner.nextInt();

        int durationSec = avgDuration * 60;
        long fileSizeBytes = (bitrate * 1000L * durationSec) / 8;
        long totalFileSizeBytes = fileSizeBytes * numSongs;

        System.out.println("Total file size: " + totalFileSizeBytes + " bytes");
        scanner.close();
    }
}
